# refers to `ansible` st2 integration pack:
# https://github.com/StackStorm/st2contrib/tree/master/packs/ansible
---
name: "chatops.playbook"
action_ref: "ansible.playbook"
description: "Run Ansible playbook"
  
formats:
  - display: "playbook <command>"
    representation:
      - "playbook '{{playbook=/opt/stackstorm/packs/st2-chatops-aliases/shipit/playbooks/test.yaml}}'"
result:
  format: |
    Ansible command `{{ execution.parameters.args }}` result: {~}
    {% if execution.result.stderr %}*Stdout:* {% endif %}
    ```{{ execution.result.stdout }}```
    {% if execution.result.stderr %}*Stderr:* ```{{ execution.result.stderr }}```{% endif %}
  extra:
    slack:
      color: "{% if execution.result.succeeded %}good{% else %}danger{% endif %}"
